import JSZip from "jszip";

export async function exportProject(generatedProject, format = "react") {
  const zip = new JSZip();
  const project = generatedProject.projectName || "extracted-design";

  if (format === "react") {
    zip.file("package.json", JSON.stringify({
      name: project,
      version: "1.0.0",
      private: true,
      scripts: { start: "react-scripts start", build: "react-scripts build" },
      dependencies: { react: "^19.0.0", "react-dom": "^19.0.0", "react-scripts": "5.0.1" },
    }, null, 2));

    zip.file("public/index.html", `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${project}</title></head><body><div id="root"></div></body></html>`);
  } else {
    zip.file("index.html", `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${project}</title><link rel="stylesheet" href="styles.css"/></head><body><div id="root"></div><script src="script.js"></script></body></html>`);
  }

  if (generatedProject.files) {
    for (const file of generatedProject.files) {
      zip.file(file.path, file.content);
    }
  }

  if (generatedProject.assets) {
    for (const asset of generatedProject.assets) {
      const dataUrl = asset.dataUrl || "";
      if (dataUrl.startsWith("data:")) {
        const base64 = dataUrl.split(",")[1];
        zip.file(asset.path, base64, { base64: true });
      }
    }
  }

  if (generatedProject.sourceScreenshots) {
    for (let index = 0; index < generatedProject.sourceScreenshots.length; index += 1) {
      const shot = generatedProject.sourceScreenshots[index];
      const dataUrl = shot.dataUrl || "";
      if (dataUrl.startsWith("data:")) {
        const base64 = dataUrl.split(",")[1];
        const label = shot.label || `reference-${index + 1}`;
        zip.file(`source-screenshots/${label}.jpg`, base64, { base64: true });
      }
    }
  }

  const extractionReport = {
    generatedAt: new Date().toISOString(),
    similarityScore: generatedProject.similarityScore || "N/A",
    sourceScreenshots: generatedProject.sourceScreenshots?.map((shot) => ({
      label: shot.label,
      y: shot.y,
      viewport: shot.viewport,
      pageHeight: shot.pageHeight,
    })) || [],
    notes: [
      "This project was generated by AI from visual analysis.",
      "Some assets may be placeholders where originals could not be extracted.",
      "Cross-origin iframes are represented as metadata only.",
      "Animations and complex interactions may be approximated.",
    ],
  };
  zip.file("EXTRACTION_REPORT.json", JSON.stringify(extractionReport, null, 2));

  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  const dataUrl = await blobToDataURL(blob);

  return {
    projectName: project,
    blob,
    dataUrl,
    size: formatBytes(blob.size),
    format,
    report: extractionReport,
  };
}

function blobToDataURL(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
