import JSZip from "jszip";

export async function exportProject(generatedProject, format = "react") {
  const zip = new JSZip();
  const project = sanitizePackageName(generatedProject.projectName || "extracted-design");
  const files = normalizeProjectFiles(generatedProject.files || []);
  smokeTestProject(files);

  if (format === "react") {
    zip.file("package.json", JSON.stringify(buildVitePackage(project), null, 2));
    zip.file("index.html", buildIndexHtml(project));
  } else {
    zip.file("index.html", `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${project}</title><link rel="stylesheet" href="styles.css"/></head><body><div id="root"></div><script src="script.js"></script></body></html>`);
  }

  for (const file of files) {
    zip.file(file.path, file.content);
  }

  if (generatedProject.assets) {
    for (const asset of generatedProject.assets) {
      const dataUrl = asset.dataUrl || "";
      if (dataUrl.startsWith("data:")) {
        const base64 = dataUrl.split(",")[1];
        zip.file(asset.path, base64, { base64: true });
      }
    }
  }

  if (generatedProject.sourceScreenshots) {
    for (let index = 0; index < generatedProject.sourceScreenshots.length; index += 1) {
      const shot = generatedProject.sourceScreenshots[index];
      const dataUrl = shot.dataUrl || "";
      if (dataUrl.startsWith("data:")) {
        const base64 = dataUrl.split(",")[1];
        const label = shot.label || `reference-${index + 1}`;
        zip.file(`source-screenshots/${label}.jpg`, base64, { base64: true });
      }
    }
  }

  const extractionReport = {
    generatedAt: new Date().toISOString(),
    similarityScore: generatedProject.similarityScore || "N/A",
    sourceScreenshots: generatedProject.sourceScreenshots?.map((shot) => ({
      label: shot.label,
      y: shot.y,
      viewport: shot.viewport,
      pageHeight: shot.pageHeight,
    })) || [],
    notes: [
      "This project was generated by AI from visual analysis.",
      "Some assets may be placeholders where originals could not be extracted.",
      "Cross-origin iframes are represented as metadata only.",
      "Animations and complex interactions may be approximated.",
    ],
  };
  zip.file("EXTRACTION_REPORT.json", JSON.stringify(extractionReport, null, 2));

  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  const dataUrl = await blobToDataURL(blob);

  return {
    projectName: project,
    blob,
    dataUrl,
    size: formatBytes(blob.size),
    format,
    report: extractionReport,
  };
}

function buildVitePackage(name) {
  return {
    name,
    private: true,
    version: "1.0.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "vite build --base ./",
      preview: "vite preview",
    },
    dependencies: {
      react: "^19.1.0",
      "react-dom": "^19.1.0",
    },
    devDependencies: {
      "@vitejs/plugin-react": "^4.3.4",
      vite: "^6.3.5",
    },
  };
}

function buildIndexHtml(project) {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(project)}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/index.jsx"></script>
  </body>
</html>`;
}

function normalizeProjectFiles(files) {
  const map = new Map();
  for (const file of files) {
    const content = getFileContent(file);
    if (!file?.path || typeof content !== "string") continue;
    const normalizedPath = normalizePath(file.path);
    map.set(normalizedPath, content);
  }

  const moduleCssPath = [...map.keys()].find((path) => /(^|\/)App\.module\.css$/i.test(path));
  if (moduleCssPath && !map.has("App.css")) {
    map.set("App.css", map.get(moduleCssPath));
    map.delete(moduleCssPath);
  }

  const appPath = map.has("App.jsx") ? "App.jsx" : [...map.keys()].find((path) => /(^|\/)App\.jsx$/i.test(path));
  if (!appPath) {
    throw new Error("AI output did not include App.jsx. Extraction was not packaged to avoid shipping a placeholder project.");
  }

  let app = map.get(appPath);
  app = normalizeAppImports(app);
  map.set("App.jsx", app);
  if (appPath !== "App.jsx") map.delete(appPath);

  if (!map.has("App.css")) {
    map.set("App.css", "");
  }

  if (!map.has("index.jsx")) {
    const srcIndex = map.get("src/index.jsx");
    map.set("index.jsx", srcIndex ? normalizeIndexImports(srcIndex) : buildIndexJsx());
    map.delete("src/index.jsx");
  }

  map.delete("public/index.html");
  map.delete("index.html");
  map.delete("package.json");

  return [...map.entries()].map(([path, content]) => ({ path, content }));
}

function normalizeAppImports(content) {
  let next = content
    .replace(/import\s+styles\s+from\s+["']\.\/App\.module\.css["'];?/g, 'import "./App.css";')
    .replace(/import\s+["']\.\/App\.module\.css["'];?/g, 'import "./App.css";');

  if (!/import\s+["']\.\/App\.css["'];?/.test(next)) {
    next = next.replace(/(import[\s\S]*?;\s*)/, `$1\nimport "./App.css";\n`);
    if (!/import\s+["']\.\/App\.css["'];?/.test(next)) {
      next = `import "./App.css";\n${next}`;
    }
  }

  next = next
    .replace(/className=\{styles\.([A-Za-z0-9_$-]+)\}/g, 'className="$1"')
    .replace(/className=\{styles\[['"]([^'"]+)['"]\]\}/g, 'className="$1"')
    .replace(/className=\{`([^`]*?)\$\{styles\.([A-Za-z0-9_$-]+)\}([^`]*?)`\}/g, 'className="$1$2$3"');

  return next;
}

function smokeTestProject(files) {
  const map = new Map(files.map((file) => [file.path, file.content]));
  const app = map.get("App.jsx") || "";
  const css = map.get("App.css");
  const index = map.get("index.jsx") || "";

  const failures = [];
  if (!app.trim()) failures.push("App.jsx is empty");
  if (!/import\s+["']\.\/App\.css["'];?/.test(app)) failures.push('App.jsx must import "./App.css"');
  if (/\bstyles\./.test(app)) failures.push("App.jsx still contains CSS module styles.* references");
  if (css == null) failures.push("App.css is missing");
  if (!/from\s+["']\.\/App\.jsx["']/.test(index)) failures.push('index.jsx must import "./App.jsx"');
  if (!/createRoot\s*\(/.test(index)) failures.push("index.jsx must mount the React app");

  if (failures.length) {
    throw new Error(`Generated project failed packaging checks: ${failures.join("; ")}`);
  }
}

function getFileContent(file) {
  if (typeof file.content === "string") return file.content;
  if (typeof file.code === "string") return file.code;
  if (typeof file.source === "string") return file.source;
  return null;
}

function normalizePath(path) {
  let next = String(path).replace(/\\/g, "/").replace(/^\/+/, "").replace(/^(\.\/)+/, "");
  if (/\.(jsx?|css)$/i.test(next)) {
    next = next.replace(/^src\//, "");
  }
  return next;
}

function normalizeIndexImports(content) {
  return content
    .replace(/from\s+["']\.\/App\.jsx["']/g, 'from "./App.jsx"')
    .replace(/from\s+["']\.\/src\/App\.jsx["']/g, 'from "./App.jsx"')
    .replace(/from\s+["']\.\/App["']/g, 'from "./App.jsx"')
    .replace(/from\s+["']\.\/src\/App["']/g, 'from "./App.jsx"');
}

function buildIndexJsx() {
  return `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`;
}

function sanitizePackageName(name) {
  return String(name)
    .toLowerCase()
    .replace(/[^a-z0-9-_]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80) || "extracted-design";
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function blobToDataURL(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
